const countries = [ 'Canada',
                    'Dubai',
                    'Japan',
                    'Germany',
                    'Maimi',
                    'China', 
                    'mali',
                    'Finland',
                    'Ireland',
                    'Europe']